DROP TABLE KLIENT;
DROP TABLE PRACOVNIK_BANKY;
DROP TABLE UCET;
DROP TABLE DISPONOVANI;
DROP TABLE OPERACE_S_UCTEM;

CREATE TABLE KLIENT (
    ID INT GENERATED AS IDENTITY NOT NULL PRIMARY KEY,
    JMENO VARCHAR(31),
    PRIJMENI VARCHAR(63),
    EMAIL VARCHAR(127),
    TELEFONNI_CISLO NUMERIC(9),
    STAT VARCHAR(31),
    MESTO VARCHAR(63),
    ULICE VARCHAR(63),
    CISLO_POPISNE NUMERIC(6),
    PSC NUMERIC(5)
);

CREATE TABLE PRACOVNIK_BANKY (
    ID INT GENERATED AS IDENTITY NOT NULL PRIMARY KEY,
    JMENO VARCHAR(31),
    PRIJMENI VARCHAR(63),
    EMAIL VARCHAR(127),
    TELEFONNI_CISLO NUMERIC(9),
    LOGIN VARCHAR(63),
    HESLO VARCHAR(127)
);

CREATE TABLE UCET (
    CISLO_UCTU INT GENERATED AS IDENTITY NOT NULL PRIMARY KEY,
    ID INT
    DATUM_ZALOZENI DATE,
    ZUSTATEK NUMERIC(10),

    VLASTNIK INT NOT NULL,
    FOREIGN KEY (VLASTNIK) REFERENCES KLIENT (ID),
);

CREATE TABLE DISPONOVANI (
    DISPONENT INT NOT NULL,
    CISLO_UCTU INT NOT NULL,

    PRIMARY KEY (DISPONENT, CISLO_UCTU),

    FOREIGN KEY (DISPONENT) REFERENCES KLIENT (ID),
    FOREIGN KEY (CISLO_UCTU) REFERENCES UCET (CISLO_UCTU)
);

CREATE SEQUENCE operace_seq
    START WITH 1
    INCREMENT BY 1;

CREATE TABLE OPERACE_S_UCTEM (
    CISLO_UCTU INT NOT NULL,
    PORADOVE_CISLO INT operace_seq.nextval,
    DATUM DATE,
    TYP NUMERIC(1),
    CASTKA NUMERIC(10),
    MENA VARCHAR(10),
    CILOVY_UCET INT,
    POPIS VARCHAR(1024),

    PROVEDL INT NOT NULL, 
    ZADAL INT NOT NULL,

    PRIMARY KEY (CISLO_UCTU, PORADOVE_CISLO),
    FOREIGN KEY (CISLO_UCTU) REFERENCES UCET (CISLO_UCTU),
    FOREIGN KEY (PROVEDL) REFERENCES KLIENT (ID),
    FOREIGN KEY (ZADAL) REFERENCES PRACOVNIK_BANKY (ID)
);
